name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.j
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Embold scan step
        inputs:
          emboldUrl:
            description: 'URL of your Embold instance'
            required: true
            default: ''
          emboldToken:
            description: 'Your Embold access token'
            required: true
            default: ''
          emboldRepoUid:
            description: 'Embold repository UID where the results will be published'
            required: true
            default: ''
        outputs:
          status:
            description: 'Status of the scan'
        runs:
          using: 'node18'
          main: 'srx/index.tsx'
        id: embold
        with:
          emboldUrl: ${{ secrets.EMB_URL }}
          emboldToken: ${{ secrets.EMB_TOKEN }}
          emboldRepoUid: ${{ secrets.EMB_REPOUID }}
      - name: Clean modules
        run: npm run clean
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
